# Generated by Django 3.2.6 on 2021-08-26 08:50

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.FileField(blank=True, storage=core.models.ZipFileStorage(), upload_to=core.models.product_image_directory_path, verbose_name='Image')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Start price')),
            ],
        ),
    ]
